# Generated by Django 2.0.5 on 2018-05-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180508_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Artical',
        ),
    ]
