# Generated by Django 2.0.5 on 2018-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180508_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
