# Generated by Django 2.0.5 on 2018-05-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_artical_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
